.TH DECODE 1 "12-01-13" "CSCI 241" "Oberlin College"

.SH NAME
.B decode
\- decodes a file

.SH SYNOPSIS
.B decode
input_stream [ output_stream ]

.SH DESCRIPTION
.B decode
decodes text with the huffman algorithm. The first argument is the input stream. The second argument is the output stream and is optional. If there is no second argument, the decoded text will be printed out standard output.

.SH AUTHOR
Shiying Zheng(Fall 2013)
Benjamin Stern(Fall 2013)

.SH BUGS
None!
