.TH ENCODE 1 "12-01-13" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
\- Encodes a file.

.SH SYNOPSIS
.B encode
input_stream [ output_stream ]

.SH DESCRIPTION
.B encode
encodes text with the huffman algorithm. The first argument is the input stream. The second argument is the output stream and is optional. If there is no second argument, the encoded text will be printed out standard output.

.SH AUTHOR
Shiying Zheng(Fall 2013)
Benjamin Stern(Fall 2013)

.SH BUGS
None!
